### PR TITLE
Scala 2.12

### PR DESCRIPTION
**Pull request by jeremyrsmith**
Scala 2.12 support (thanks @cripsywalrus!)

### CODE REVIEW

**Comment by mxl** [comment]
Could maintainers merge this PR and release new version? Thanks!

**Comment by jeremyrsmith** [comment]
@mxl I haven't had a chance to figure out why tests are failing for 2.12 (seems to be a deadlock since tests just hang after completing)

**Comment by clhodapp** [comment]
Potentially (but not necessarily) relevant is the fact that the following is printed under 2.12 but not 2.11:
```
Jan 10, 2017 3:16:20 PM org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool
WARNING: Failed to get all worker threads ready within 10 second(s). Make sure to specify the executor which has more threads than the requested workerCount. If unsure, use Executors.newCachedThreadPool().
```

See also https://groups.google.com/forum/#!topic/finaglers/rjAKtJVwaS8

**Comment by clhodapp** [comment]
FWIW, you do get that warning but you don't get the deadlock if tut is disabled.

**Comment by clhodapp** [comment]
In fact, you can look at the generated tut markdown files and see that it is getting stuck the first time it comes across a lambda. Perhaps related to http://scala-lang.org/news/2.12.0#object-initialization-locks-and-lambdas. Putting this in `build.sbt` will disable tut under 2.12 and prevent the deadlock:

```
test in Test in `finagle-postgres` := Def.taskDyn {
  (test in Test in `finagle-postgres`).value
  (test in Test in `finagle-postgres-shapeless`).value
  (scalaVersion in docs).value.split('.').toList match {
    case List("2", "11", x) => Def.task { (tut in Compile in docs).value; () }
    case other => Def.task { () }
  }
}.value
```

**Comment by crispywalrus** [comment]
@clhodapp could you open a pr against this branch with your tut fix?

**Comment by mxl** [comment]
@jeremyrsmith Could you make a new release with Scala 2.12 support?

**Comment by fwbrasil** [comment]
@jeremyrsmith do you have plans to push the new release to maven central? Is there something we could help with? We're waiting for it to release quill for 2.12.

**Comment by jeremyrsmith** [comment]
@mxl @fwbrasil Unfortunately it seems to be broken in 2.12 currently. I think upgrading finagle to 6.43.0 might help, but there were also some breaking API changes from 6.41.0 that have to be updated. I probably won't have time to do this until the weekend (any help is welcome though!)

**Comment by mdedetrich** [comment]
2.12.2 was just released, which may solve the problem @jeremyrsmith @mxl @fwbrasil http://www.scala-lang.org/news/releases-1Q17.html

**Pull request merged**
