### PR TITLE
 upgrade netty

### PR DESCRIPTION
**Pull request by jilen**
Upgrade to `finagle-netty4`,
But there are buf leaks. Because `RowImpl`  holds buffers for future value decoding.
So UnpooledByteBufAllocator is enabled by default currently.

### CODE REVIEW

**Comment by leonmaia** [comment]
Thanks for contributing @jilen. I'll have a look as soon as possible.

**Comment by clhodapp** [comment]
A note on the value of this (in case it's not clear): I suspect that for a lot of us (definitely for myself), finagle-postgres is the only client left on netty-3. Thus, getting it onto netty-4 could potentially shrink the dependency footprint & thread counts for our apps.

**Comment by clhodapp** [comment]
Finagle has dropped support for Netty 3 in version 19.04, so something like this will have to go in for finagle-postgres to go beyond 19.03.

**Comment by jeremyrsmith** [comment]
I made a previous attempt at this about a year ago (#74) but it turns out to be somewhat tricky, because memory management is very different in Netty 4 and it's not super clear where all the boundaries are between user code and finagle-postgres. 

@bryce-anderson left a lot of useful comments on #74 that may be handy in figuring it out here. I think with enough effort it would be doable to make this work properly, but nobody seems to have the time (I certainly don't 😞 – hopefully someone who uses this library will contribute some time)

**Comment by clhodapp** [comment]
One big difference between your attempt and @jilen's, I think, is that @jilen simply gave up on buffer pooling in order to make buffer leaks non-problematic at the cost of performance. Overall, it would obviously be great to reach a world where we aren't allocating a bunch of buffers unnecessarily but I personally think that it's a lot better to have a TODO (that honestly may sit undone for a very long time) for a noncritical performance task vs getting stuck behind on what will eventually become an increasingly-old version of Finagle. You're right though: this all comes down to time, which is a very precious commodity.

On that note, thanks for all the time you've given to this project so far!

**Comment by jilen** [comment]
@clhodapp @jeremyrsmith   Netty 4.0.x and Netty 3.x both use unpooled allocator by default. So I thought it is ok to stick with it for now. And  once we make all decoding done inside netty pipeline in the future, we could trun to pooled bytebuffer without any pain.

**Comment by jeremyrsmith** [comment]
Hmm, I must have misinterpreted the first PR comment. But now that you mention it I see the magic line where the allocator is forced to the unpooled allocator. If it doesn't introduce memory leaks then it's a :+1: from me.

**Comment by jeremyrsmith** [comment]
I'd like to go ahead and merge this, because it's going to start blocking people from upgrading their finagle version. I'm not sure I still understand how the release process works, though. @vkostyukov or @leonmaia?

**Comment by leonmaia** [comment]
I agree, @jeremyrsmith, I started working on your old PR yesterday but it's not a simple task. I also think it's best to merge this.

**Pull request merged**
