### PR TITLE
Enable Autoreleases

### PR DESCRIPTION
**Pull request by vkostyukov**
This PR enables autoreleases as discussed in #92. It kicks in a release (fully automated, no human interaction is required, including promoting staging artifacts in Sonatype) when a version is updated to a non-SHAPSHOT in `version.sbt`. So anyone with a push access to a repository can cut releases now.

When release is performed, it bumps a version to a next one and commits the changes.

NOTE: We had to give up the build matrix. All PRs are kicking in a single job now that runs tests for cross-version Scala.

As a nice bonus, this publishes SNAPSHOT on each push to master.

The credentials I used (everything is encrypted and can only be decrypted by Travis CI):
 - I generated a new deploy_key and added that to the repo (Github doesn't allow you to share them)
 - I used both secring and pubring gpg keys I generated for Finch releases (finagle-oauth2, finch-oauth2 use them too)
 - I used `credentials.sbt` with my Sonatype credentials (I have write access to all Finagle Org) and the GPG passphrase
 - I generated an ENC password used with aes-256 encoding via 1Password

### CODE REVIEW

**Comment by leonmaia** [comment]
Build failure seems unrelated, I'm restarting the build.

**Comment by leonmaia** [comment]
```
[error] java.io.IOException: Access to URL https://oss.sonatype.org/content/repositories/snapshots/io/github/finagle/finagle-postgres_2.12/vk/autoreleases-SNAPSHOT/finagle-postgres_2.12-vk/autoreleases-SNAPSHOT.pom was refused by the server: Forbidden
```
It seems like the Sonatype plugin is not finding the credentials.

**Comment by vkostyukov** [comment]
Turns out my write access was limited to `com.github.finagle`, while finagle-posgres is published under `io.github.finagle`. I asked for new write access here: https://issues.sonatype.org/browse/OSSRH-44411. It was granted and the build should be green once new credentials are propagated. I will keep restarting it in the meantime.

Update: now I'm confused. Looks like I already had access in https://issues.sonatype.org/browse/OSSRH-17056. Will look into that today more.

**Comment by vkostyukov** [comment]
Going to try changing the group id to see if that's about me no having access to `io.github` or about credentials not loading correctly.

**Comment by vkostyukov** [comment]
So changing the group id helps. I'm going to reach out to Sonatype people and ask them double-check my credentials again.

**Comment by vkostyukov** [comment]
Should be green now.

**Review by leonmaia — APPROVED** [review]
Awesome work! 🚀

**Pull request merged**
