### PR TITLE
[WIP] Update dependencies

### PR DESCRIPTION
**Pull request by golem131**

### CODE REVIEW

**Comment by jeremyrsmith** [comment]
@golem131 There's a conflict since I just released 0.4.3. Can you resolve it and then we'll release 0.4.4? Sorry about that!

**Comment by jeremyrsmith** [comment]
@golem131 never mind - github has a tool for that now!

**Comment by viktortnk** [comment]
@jeremyrsmith any plans to update to Finagle 7.0.0 series in short term?
Thanks

**Comment by viktortnk** [comment]
issued #61

**Comment by jeremyrsmith** [comment]
I think we're past this now. Apologies for the lack of attention!

**Pull request closed without merging**
