### PR TITLE
Multi-statement DDL, UUIDs

### PR DESCRIPTION
**Pull request by jeremyrsmith**
- Support CREATE EXTENSION completion tag
- Support multi-statment DDL
- Support uuid type mapping to java.util.UUID

### CODE REVIEW

**Comment by jeremyrsmith** [comment]
Also bumps finagle dependency to latest version

**Comment by vkostyukov** [comment]
Looks good to me! Let me see if I can get somebody else to have a look.

**Comment by vkostyukov** [comment]
@matterkkila, @mairbek, @yolken Any chance one of you want to have a look?

**Comment by jeremyrsmith** [comment]
Can this be merged?  finagle-postgres literally does not work at all with the current version of Finagle.

```
java.lang.AbstractMethodError: com.twitter.finagle.postgres.codec.PgCodec$$anon$1.prepareConnFactory(Lcom/twitter/finagle/ServiceFactory;Lcom/twitter/finagle/Stack$Params;)Lcom/twitter/finagle/ServiceFactory;
```

This would be fixed by merging this PR.

**Pull request merged**
