### PR TITLE
Manual transaction support and prepared perform

### PR DESCRIPTION
**Pull request by jeremyrsmith**
- CommandComplete tags for BEGIN, SAVEPOINT, ROLLBACK, COMMIT
- prepareAndExecute(query, params) method to conveniently execute a paramaterized
  statement that is not expected to return anything (i.e. UPDATE)

### CODE REVIEW

**Comment by travisbrown** [comment]
This looks reasonable to me. Any thoughts, @yolken, @penland365?

Would you mind adding a test, @jeremyrsmith? An integration test on the model of `prepareAndQuery` should be fine for now.

**Comment by jeremyrsmith** [comment]
Added a test for prepareAndExecute

**Comment by jnd71** [comment]
So I'm not 100% sure on this.  Postgres transactions aren't really State Machine Actions as far as the life cycle of each connection is concerned - in terms of a the actual connection, when a client issues a command against the server for a PreparedStatement, it does a dance through `Prepare` => `Bind`=> `Execute`. There really isn't such a thing as a `BEGIN` `SAVEPOINT` `ROLLBACK` `COMMIT` BackEnd message - all of that should be explicitly stated in the SQL itself.  From the [docs](http://www.postgresql.org/docs/8.3/static/tutorial-transactions.html):

``` SQL
BEGIN;
UPDATE accounts SET balance = balance - 100.00
    WHERE name = 'Alice';
SAVEPOINT my_savepoint;
UPDATE accounts SET balance = balance + 100.00
    WHERE name = 'Bob';
-- oops ... forget that and use Wally's account
ROLLBACK TO my_savepoint;
UPDATE accounts SET balance = balance + 100.00
    WHERE name = 'Wally';
COMMIT;
```

In order to actually cancel a Query, we have to issue a `CancelRequest` containing a secret key + `PID` given during the startup phase - on a separate Connection. I don't believe we are storing that key right now, and I don't see a `CancelRequest` implementation currently.

Given the current implementation of `CommandCompleteStatus` Messages in [BackendMessages.scala](https://github.com/jeremyrsmith/finagle-postgres/blob/master/src/main/scala/com/twitter/finagle/postgres/messages/BackendMessages.scala) , I'm OK w/ leaving leaving those extra Transaction statements in there, but we shouldn't be changing the State of the Connection Machine - it should still be an `BUSY` State awaiting normal Server Issued Messages.  From the standpoint of `Finagle`, a Transaction should like identical to any other issued Query - we don't have control over it once it Postgres beings to process it anyways.

**Comment by jeremyrsmith** [comment]
The `CancelRequest` is not related to transactions per se - it's related to long-running queries in general.  It's used, for example, by psql when you ^C on a running query.

The only changes proposed are incorporating the CommandComplete tags for transaction lifecycle commands, so that finagle-postgres can acknowledge them.  The commands are issued through queries, just like you said above.  But if you issue a query, i.e.

``` scala
client.exec("BEGIN")
```

then when the server returns a BEGIN CommandComplete message, finagle-postgres will currently throw an error, rather than going to Sync and ReadyForQuery.  This change is intended to correct that, not to implement any kind of complicated transaction mechanics.

**Comment by jeremyrsmith** [comment]
By the way, Travis only failed the build because it was having problems fetching dependencies.

Edit: By which I mean Travis CI, not @travisbrown XD

**Comment by jnd71** [comment]
OK, this is making a bit more sense to me - I see what you're going for. I was thrown by the inclusion of `prepareAndExecute` - if you issue a command like this:

``` scala
  client.exec("BEGIN; UPDATE FOO");
```

postgres will transform this during the `Parse` phase into

``` SQL
BEGIN;
UPDATE FOO;
COMMIT;
```

and the `CommandStatus` returned should be `UPDATE`. I didn't realize you were issuing raw transaction commands.

@travisbrown I'm a :+1:

**Pull request closed without merging**
