### PR TITLE
Ensure that we close `service` and 'constFactory` when transactions fail

### PR DESCRIPTION
**Pull request by afine**
We ran into an issue where our pool_size for the postgres service would slowly but invariably grow. 

After some investigation it turned out that connections from failed transactions would never leave the connection pool. The reason for this appears to be failure to clean up if the `ROLLBACK` or `COMMIT` query fail.

This patch changes `inTransaction` to make sure that `service.close()` and `constFactory.close` are executed if the `ROLLBACK` or `COMMIT` queries fail.

### CODE REVIEW

**Comment by afine** [comment]
I don't believe the ci failure is related to this PR.

**Comment by vkostyukov** [comment]
This makes sense to me @afine! Thanks for the PR. 

@leonmaia Any chance you can take a look?

**Comment by afine** [comment]
@vkostyukov @leonmaia Is there anything else I need to do?

**Comment by leonmaia** [comment]
Looks good @afine, can you please squash your commits and add your PR description in the commit message?

**Comment by afine** [comment]
@leonmaia sorry for the delay. everything should be good to go.

**Pull request merged**
